version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=forum_hub
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local